### ISSUE TITLE
User id is always IP address

### ISSUE THREAD

**Issue by timiyay** [bugsnag/bugsnag-js#171] opened 2016-08-08 02:59 UTC
I'm experimenting with Bugsnag, and loving it so far.

I'm hitting an annoyance, when adding `user` metadata to my exception - my user ID is being ignored, and the default IP address is always being used instead.

I'm using the standard user metadata like:

```js
    user: {
      id: '6',
      email: 'test@example.com',
      name: 'testy mctestington'
    }
```

Things I've tried:

* deleting all of my error events, and logging again
* ensuring that `id` is cast to a string
* switching from `bugsnag-2.min.js` to `bugsnag-3.min.js`

**Comment by jacobmarshall** [comment] 2016-08-08 03:05
> switching from `bugsnag-2.min.js` to `bugsnag-3.min.js`

Does this happen for you when using v2? Because I just checked a recent event in my Bugsnag dashboard (in a project using v2) and I'm seeing the correct user ID.

![screenshot 2016-08-08 15 04 00](https://cloud.githubusercontent.com/assets/4710291/17468197/6dce7850-5d79-11e6-90b4-03da693e7f6e.png)

**Comment by jacobmarshall** [comment] 2016-08-08 03:06
Regardless, it sounds like a server side issue to me. Possibly with the v3 `payloadVersion`?

**Comment by timiyay** [comment] 2016-08-08 03:31
Thanks for the extra info @jacobmarshall.

Still digging. I think you're right in that's its a server-side issue for Bugsnag. I'm inspecting the request being sent from my app, and there's no mention of the client IP, which is what's being used instead of ID. Furthermore, I was able to confirm that the ID is being included in the request:

```
...my request url... &metaData%5Buser%5D%5Bid%5D=6&metaData%5Buser%5D%5Bemail%5D=test%40example.com&metaData%5Buser%5D%5Bname%5D=testy%20mctestington
```

**Comment by GrahamCampbell** [comment] 2016-08-08 08:27
If you send a userId and a user, the server will use the userId, and discard the user I think. Make sure you only send a user.

**Comment by jacobmarshall** [comment] 2016-08-08 08:30
Thanks @GrahamCampbell however userId was removed in v3 of the bugsnag-js notifier. Also the issue is with the server overriding the user ID field. I don't think there's any issue with the notifier or how this user is using it.

**Comment by GrahamCampbell** [comment] 2016-08-08 08:31
Hmmm. The upcoming PHP notifier also uses the v3 payload, and I'm not seeing any issues there, so I don't think this is a server side issue.

**Comment by jacobmarshall** [comment] 2016-08-08 08:35
Fair enough. Would you be able to provide a screenshot of (or link to) the error in your Bugsnag dashboard, @timiyay?

Bare in mind also that the endpoint is different for bugsnag-js, so could the IP be getting overridden there?

**Comment by jacobmarshall** [comment] 2016-08-08 08:41
I got out of bed to give it a try 😛 

I am able to replicate this using the bugsnag-js 3.0.0.

<img width="406" alt="screenshot 2016-08-08 20 39 16" src="https://cloud.githubusercontent.com/assets/4710291/17474109/6baad666-5da8-11e6-8489-b0bb330f528e.png">
<img width="237" alt="screenshot 2016-08-08 20 39 22" src="https://cloud.githubusercontent.com/assets/4710291/17474110/6bae758c-5da8-11e6-99a8-ad25b04211fc.png">

**Comment by GrahamCampbell** [comment] 2016-08-08 08:42
Oh, this is because the user is not metadata. You need to set the user rather than putting it in metadata. The metadata is a different field on the payload.

**Comment by jacobmarshall** [comment] 2016-08-08 08:44
Ah, that's right. Good spotting.

**Comment by timiyay** [comment] 2016-08-08 08:46
orly? that's no entirely clear from the docs, but oh well.

Strangely, even though I'm putting `user` inside the metadata, the other params are making it into the `User` tab in my bugsnag dashboard

![bugsnag_user_id](https://cloud.githubusercontent.com/assets/1470250/17474237/4cd90ed4-5d98-11e6-9d33-fbb1a71443e3.png)

Confused...

**Comment by jacobmarshall** [comment] 2016-08-08 08:49
The user object is kind of treated a bit special.

https://docs.bugsnag.com/api/error-reporting/#per-session-settings

Metadata fields are not searchable from within bugsnag, but user data is.

<img width="309" alt="screenshot 2016-08-08 20 48 22" src="https://cloud.githubusercontent.com/assets/4710291/17474341/85d81b60-5da9-11e6-8137-f2dcd9ca1d69.png">

**Comment by timiyay** [comment] 2016-08-08 08:50
OK thanks for the help, I've opened a ticket in the library I'm using (https://github.com/binhums/ember-cli-bugsnag/issues/48#issuecomment-238170125) to add support for a top-level `user` object.

**Comment by jacobmarshall** [comment] 2016-08-08 08:52
Great, no problem. Thank you @GrahamCampbell for spotting that 😛 

Please feel free to close this issue 😃

**Comment by jacobmarshall** [comment] 2016-08-08 08:53
> I get this with both v2 and v3 of BugsnagJS BTW.

Yes there was no change made to user data in v3.

**Closed** 2016-08-08 08:54 UTC

**Comment by nihp** [comment] 2019-10-10 07:02
What is the difference between userId and UDID and how the user id is generated in bugsnag?

Details please

**Comment by abigail-bugsnag** [comment] 2019-10-11 09:41
Hi @nihp, information on the automatically captured data for bugsnag-js is available [here](https://docs.bugsnag.com/platforms/javascript/automatically-captured-data/). For JS, the User ID is set to the user's IP address by default.

**Comment by nihp** [comment] 2019-10-11 12:11
Then the UDID? and dsymUDID

**Comment by abigail-bugsnag** [comment] 2019-10-11 13:34
@nihp what platform are you using? React Native? If so, then the automatically captured data [for Android](https://docs.bugsnag.com/platforms/android/automatically-captured-data/) and [for iOS](https://docs.bugsnag.com/platforms/ios/automatically-captured-data/) is probably what you are looking for.
In Android, the User ID and Device ID are set to a randomly generated UUID which Bugsnag uses to identify the individual application on a device.
In iOS, the Device ID is a hash of device and app specific data.
The dSYM UUIDs are not generated by Bugsnag. These will be generated by Apple and are used to uniquely identify the dSYMs needed for your application version.

If you have further questions on this, please write in to support@bugsnag.com.

**Comment by nihp** [comment] 2019-10-12 04:20
@abigail-bugsnag 
Just asked to confirm my doubts. Thanks for your clarification
