### ISSUE TITLE
Angular Plugin es6

### ISSUE THREAD

**Issue by driverpt** [bugsnag/bugsnag-js#482] opened 2019-02-15 18:11 UTC
Bugsnag library is throwing an error when i configure TypeScript (via tsconfig) with es6 as target.

The error is somewhere in the index.js constructor stating that the you can only instantiate via the `new` keyword.

To replicate:
 - Create a Bugsnag Angular App
 - Set tsconfig.json target to ES6

**Comment by bengourley** [comment] 2019-02-19 10:40
I have confirmed that this is an issue.

It is because we compile the `@bugsnag/plugin-angular` module (which is authored in TS) is compiled to ES5-compatible JS, and there is limited interop between native classes and "classes" that are simluated with ES5 code.

Switching the `tsconfig.json` option `"target": "es6"` for our module makes this issue go away, but we'd need to explore the ramifications of that. It could potentially break people's projects – though maybe not as all Angular projects require a build step and are capable of consuming ES6 code?

**Comment by tomlongridge** [comment] 2019-05-31 14:47
Fixed in #540 and released in v6.3.0.

**Closed by tomlongridge** 2019-05-31 14:47 UTC
Labels: scheduled
