### ISSUE TITLE
library not found for -lBugsnagReactNative

### ISSUE THREAD

**Issue by lalitkumarrock** [bugsnag/bugsnag-js#1362] opened 2021-04-16 11:23 UTC
Hii ,

When trying to install the @bugsnag/react-native library . In android it's working fine. When i install the pod i'm getting this issue . 

(https://user-images.githubusercontent.com/82652040/115017439-2a9b2c80-9ed4-11eb-8a15-75bb559ffbb8.png)

**Comment by xander-jones** [comment] 2021-04-16 15:35
Hey @lalitkumarrock, are you installing `@bugsnag/react-native` manually? I wouldn't expect to be installing the pods in the `Podfile` through Xcode. This needs to be run from a terminal with `pod install` from your ios directory: https://docs.bugsnag.com/platforms/react-native/react-native/manual-setup/#ios

Which steps have you taken so far?

**Comment by crrobinson14** [comment] 2021-04-21 17:31
I am having the same problem. Using just the standard React Native package installation approach (`yarn add @bugsnag/react-native` -> installs 7.9.4 FYI, followed by `cd ios && pod install` for auto-linking) in a fresh React Native 0.64.0 project produces this during compilation:

```    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Xlinker -rpath -Xlinker /usr/lib/swift -target x86_64-apple-ios10.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator -L -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/BugsnagReactNative -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/CocoaAsyncSocket -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/DoubleConversion -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/FBReactNativeSpec -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/Flipper -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/Flipper-DoubleConversion -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/Flipper-Folly -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/Flipper-Glog -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/Flipper-PeerTalk -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/Flipper-RSocket -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/FlipperKit -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/RCT-Folly -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/RCTTypeSafety -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/RNCAsyncStorage -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/RNDateTimePicker -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/RNDeviceInfo -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/RNFS -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/RNFastImage -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/RNGestureHandler -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/RNKeychain -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/RNScreens -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-Core -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-CoreModules -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-RCTAnimation -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-RCTBlob -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-RCTImage -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-RCTLinking -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-RCTNetwork -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-RCTSettings -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-RCTText -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-RCTVibration -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-cxxreact -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-jsi -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-jsiexecutor -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-jsinspector -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/React-perflogger -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/ReactCommon -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/ReactNativeExceptionHandler -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/SDWebImage -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/SDWebImageWebPCoder -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/WatermelonDB -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/Yoga -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/YogaKit -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/glog -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/libevent -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/libwebp -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/react-native-image-picker -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/react-native-netinfo -L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/rn-fetch-blob -F/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator -F/Users/chad/projects/awarnys/Awarnys/ios/Pods/OpenSSL-Universal/Frameworks -F/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OpenSSL -filelist /Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Intermediates.noindex/Awarnys.build/Debug-iphonesimulator/Awarnys.build/Objects-normal/x86_64/Awarnys.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Intermediates.noindex/Awarnys.build/Debug-iphonesimulator/Awarnys.build/Objects-normal/x86_64/Awarnys_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Intermediates.noindex/Awarnys.build/Debug-iphonesimulator/Awarnys.build/Objects-normal/x86_64/Awarnys.swiftmodule -ObjC -lBugsnagReactNative -lCocoaAsyncSocket -lDoubleConversion -lFBReactNativeSpec -lFlipper -lFlipper-DoubleConversion -lFlipper-Folly -lFlipper-Glog -lFlipper-PeerTalk -lFlipper-RSocket -lFlipperKit -lRCT-Folly -lRCTTypeSafety -lRNCAsyncStorage -lRNDateTimePicker -lRNDeviceInfo -lRNFS -lRNFastImage -lRNGestureHandler -lRNKeychain -lRNScreens -lReact-Core -lReact-CoreModules -lReact-RCTAnimation -lReact-RCTBlob -lReact-RCTImage -lReact-RCTLinking -lReact-RCTNetwork -lReact-RCTSettings -lReact-RCTText -lReact-RCTVibration -lReact-cxxreact -lReact-jsi -lReact-jsiexecutor -lReact-jsinspector -lReact-perflogger -lReactCommon -lReactNativeExceptionHandler -lSDWebImage -lSDWebImageWebPCoder -lWatermelonDB -lYoga -lYogaKit -lglog -llibevent -llibwebp -lreact-native-image-picker -lreact-native-netinfo -lrn-fetch-blob -lstdc++ -framework AudioToolbox -framework CFNetwork -framework ImageIO -framework JavaScriptCore -framework MobileCoreServices -framework OpenSSL -framework Security -framework UIKit -ObjC -lc++ -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Intermediates.noindex/Awarnys.build/Debug-iphonesimulator/Awarnys.build/Awarnys.app-Simulated.xcent -lPods-Awarnys -Xlinker -dependency_info -Xlinker /Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Intermediates.noindex/Awarnys.build/Debug-iphonesimulator/Awarnys.build/Objects-normal/x86_64/Awarnys_dependency_info.dat -o /Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/Awarnys.app/Awarnys
ld: warning: directory not found for option '-L-L/Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-diuoahfygjqiqdefetlzyahqxuig/Build/Products/Debug-iphonesimulator/BugsnagReactNative'
ld: library not found for -lBugsnagReactNative
```

**Comment by johnkiely1** [comment] 2021-04-23 12:31
Hi @crrobinson14, 

I'm not able to reproduce the behaviour you are seeing, a fresh project using `react-native init <projectname> `followed by the steps you listed above compiles correctly for me with no errors. This is also using RN 0.64.0.  

How did you create your new project? Would you have an example project you could share with us that demonstrates this error? 

Thanks

**Comment by xander-jones** [comment] 2021-05-04 08:37
Hi @crrobinson14 &B @lalitkumarrock, couple of additional things you may want to try: check that your CocoaPods version is up to date, especially if you're [using Xcode 12+](https://blog.cocoapods.org/CocoaPods-1.10.0-beta/), and clean out your project before re-building. 
* Run `cd ios && xcodebuild clean && cd ../` to clean out your iOS project.
* Use the `--reset-cache` option to clear out the RN cache: https://stackoverflow.com/questions/46878638/how-to-clear-react-native-cache.

Let us know if you've a repro example of this error as above.

**Comment by mattdyoung** [comment] 2021-05-21 11:25
Closing for now but happy to re-open if you can share a way for us to reproduce.

**Closed by mattdyoung** 2021-05-21 11:25 UTC
Labels: awaiting feedback
