### ISSUE TITLE
Execution failed for task ':app:externalNativeBuildCleanDebug'.

### ISSUE THREAD

**Issue by mMarcos208** [bugsnag/bugsnag-js#2038] opened 2023-11-14 22:29 UTC
### Describe the bug

> Task :app:externalNativeBuildCleanDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildCleanDebug'.
> [CXX1409] /home/marconi/Documentos/AgroHUB.Mobile/android/app/.cxx/Debug/3x5gl5a1/armeabi-v7a/android_gradle_build.json : expected buildFiles file 'project/node_modules/@bugsnag/react-native/android/build/generated/source/codegen/jni/CMakeLists.txt' to exist

### Steps to reproduce
1. set newArchEnabled=true in gradle.properties 
2. yarn start
2. yarn android

### Environment
* Bugsnag version:     "@bugsnag/plugin-react-navigation": "^8.0.0-alpha.1", "@bugsnag/react-native": "^8.0.0-alpha.1"
* React Native version: "react-native": "0.72.6",

**Comment by clr182** [comment] 2023-11-21 11:16
Hi @mMarcos208 
I have tried reproducing your issue and have not been able to do so. Setting `newArchEnabled=true` has not resulted in a failed build for me. Could you please run your build again with the --verbose flag attached and sharing the output with us for further investigation? 

The error seems to indicate that this is possibly due to a faulty or corrupt NDK installation, it may be worth reinstalling your NDK via the SDK Manager

**Comment by mclack** [comment] 2024-03-14 13:59
Hi @mMarcos208 

As there hasn't been any activity here for a while, we are now closing this issue.

If you continue to experience issues, please feel free to reopen this issue, or open a ticket with us directly by contacting [support@bugsnag.com](mailto:support@bugsnag.com).

**Closed by mclack** 2024-03-14 13:59 UTC
Labels: awaiting feedback
