### ISSUE TITLE
Prevent duplicate NetInfo calls

### ISSUE THREAD

**Issue by nferrara100** [bugsnag/bugsnag-js#1267] opened 2021-01-26 12:36 UTC
### Description
My team currently uses Bugsnag Expo which depends on plugin-react-native-connectivity-breadcrumbs which depends on [@react-native-community/netinfo](https://github.com/react-native-netinfo/react-native-netinfo). This works fine for the bugsnag plugin by itself, but in our app we also use NetInfo. As a result NetInfo makes the same duplicate request to generate_204, once for our app's version of NetInfo, and once for Bugnsnag. This isn't the end of the world, but it looks a little sloppy and I'd rather fix it.

**Describe the solution you'd like**
I think making @react-native-community/netinfo a peer dependency would solve the issue, since there would no longer be multiple slightly different versions of NetInfo in the app. There would also need to be an option to disable NetInfo configuration in Bugsnag to prevent conflicts.

**Describe alternatives you've considered**
Ignoring it, but it gets quite annoying in the debugger and although the requests are small they do add up over the long term in data usage for frequent users.

**Additional context**
Thanks for keeping this maintained! It's an extremely useful tool.

**Comment by yousif-bugsnag** [comment] 2021-02-11 12:40
Hey @nferrara100,

This is a difficult one - making NetInfo a peer dependency wouldn't work for people who don't use NetInfo, since peer dependencies aren't automatically installed. Using a looser version constraint may fix the issue, but we keep the NetInfo version exactly in sync with Expo in order to avoid native compatibility issues.

To resolve this we'd recommend that you depend exactly on the version of NetInfo that we do (this is also the exact version Expo bundles the native code for) - the package should then be deduped by npm/yarn.

**Comment by nferrara100** [comment] 2021-02-19 11:52
Thank you for your response, @yousif-bugsnag. I see how it's very tricky. Not sure of the best solution myself, but wanted to bring it to your attention. 

I'm using the latest version of Bugsnag and the Expo version of NetInfo (5.9.7). I deleted my `yarn.lock` file today so I have a clean install of everything. You are correct that updating prevented my project from sending its own separate request, but within Bugsnag's own package there are two versions of NetInfo so I now have two requests from Bugsnag.

`@bugsnag/plugin-react-native-connectivity-breadcrumbs@^7.7.0` uses `@react-native-community/netinfo 5.9.6` while `@bugsnag/delivery-expo@^7.7.0` uses `@react-native-community/netinfo 5.9.7`. 

Furthermore, if I attempt to call `NetInfo.configure()` I have three requests because my request is no longer combined with Bugsnag's.

**Comment by xander-jones** [comment] 2021-02-23 13:58
@nferrara100, both should be using `@react-native-community/netinfo 5.9.7`, we're already planning to add a fix for this, we'll let you know as soon as this is available in a release.

> Furthermore, if I attempt to call NetInfo.configure() I have three requests because my request is no longer combined with Bugsnag's.

It would be good to revisit this after the update to see if this issue still persists.

**Comment by nferrara100** [comment] 2021-03-05 10:19
```
NetInfo.configure({
    reachabilityRequestTimeout: 20000,
    reachabilityUrl: "https://example.com/generate_204/",
});
```

**Comment by xander-jones** [comment] 2021-03-05 11:19
As timing would have it, we've just released https://github.com/bugsnag/bugsnag-js/releases/tag/v7.8.2 which bring the versions of Netinfo inline with Expo's version, I'd expect this to now de-dupe calls to Netinfo. Please let us know if this is persists to cause any issues for you.

**Comment by nferrara100** [comment] 2021-03-08 12:01
I can confirm that the above configuration still causes duplicate requests after the update. Both Bugsnag and my app are using the same exact version of NetInfo. If I remove the above configuration Bugsnag and my app share the same request as intended.

**Comment by nferrara100** [comment] 2021-03-08 12:03
Good news is there is only 1 extra request for Bugsnag and not two now.

**Comment by mattdyoung** [comment] 2021-03-10 14:58
Do you have a simple reproduction case you can share that demonstrates the remaining issue with the single duplicated request?

**Comment by mattdyoung** [comment] 2021-03-26 11:05
@nferrara100 
We'd be happy to re-open this if you can share how to reproduce.

**Closed by mattdyoung** 2021-03-26 11:05 UTC
Labels: bug, released
