### ISSUE TITLE
Self is not defined - Bugsnag/js

### ISSUE THREAD

**Issue by sayo96** [bugsnag/bugsnag-js#1725] opened 2022-04-20 09:25 UTC
### Steps to reproduce
1.  I was trying to add bugsnag to my node api and i was following the steps mentioned here https://docs.bugsnag.com/platforms/javascript/
2.  Everything was working normally but suddenly i ran into this error when i started my hapi server with `npm start`
3.  See error
<img width="1240" alt="Screenshot 2022-04-20 at 2 40 45 PM" src="https://user-images.githubusercontent.com/26695583/164193854-b012411a-2d28-4258-bebb-cfa31bc1f245.png">

### Environment
* Bugsnag version: 7.16.2

* Server framework version (if any):
    * Hapi ^16.0.3:
* Node version : 14.19.1
* Device : Apple  M1 Pro macbook pro

I did not do anything crazy with the setup. I just installed bugsnag -> created a project in bugnsag dashboard -> went on with the steps mentioned in the docs.

**Code:**
```
var Bugsnag = require('@bugsnag/js');
 Bugsnag.start({
      apiKey: process.env.BUGSNAG_NOTIFIER_KEY,
      appVersion: require('../package.json').version
    });
```

<details><summary>Error messages:
</summary>

```
ReferenceError · self is not defined
```
</details>

**Comment by sayo96** [comment] 2022-04-22 02:34
I was importing the bugsnag js file like you have mentioned when i ran into this

**Comment by luke-belton** [comment] 2022-04-22 14:28
hi @sayo96 - we're struggling to see a mechanism by which this would occur, perhaps an IntelliCode plugin or similar autocompleted the `require` statement in your IDE? I found the original error in your Bugsnag dashboard and it looks like this occurred in a local development environment?

I'm going to close this issue for now as the issue looks to be transient, but if you see this again and are able to provide us with a cut-down reproduction example demonstrating the issue we'd be more than happy to look into this further. Feel free to send this to support@bugsnag.com 👍

**Closed by luke-belton** 2022-04-22 14:28 UTC
Labels: awaiting feedback

**Comment by luke-belton** [comment] 2022-04-22 14:53
Hi @sayo96, I've just created a simple Hapi server following the steps at https://hapi.dev/tutorials/?lang=en_US#-installing-hapi, and the steps in our Node.js [installation guide](https://docs.bugsnag.com/platforms/javascript/). Unfortunately I haven't been able to reproduce the issue you were seeing.

Looking at the screenshot you shared above, it looks like the following was included in the source code within your `server/controllers/tasks.js` file (lines 15 to 21):
```
var moment = require('moment');
var recurringTasksHelper = require('../utils/recurringTasks');
var TaskConstants = require('../constants/task');
const { default: Bugsnag } = require('@bugsnag/browser');
// var sentry = require('../sentry');

const RRule = rruleModule.RRule;
```

It's the inclusion of the `const { default: Bugsnag } = require('@bugsnag/browser');` line in your source code that appears to be causing this crash, rather than something happening inside the Bugsnag plugin itself. As I originally suggested, you'd want to change that to `var Bugsnag = require('@bugsnag/js');` to avoid the crash.

If you are able to provide a reproduction example of this where you've included `var Bugsnag = require('@bugsnag/js');`, we'd be more than happy to investigate.
