### ISSUE TITLE
react native expo:Bugsnag.getPlugin('react') returns undefined

### ISSUE THREAD

**Issue by seyaobey** [bugsnag/bugsnag-js#883] opened 2020-06-10 20:50 UTC
I have exactly followed the guidelines about installing`bugsnag` with a [react native expo](https://docs.bugsnag.com/platforms/react-native/expo/) application. Now I would like to wrap my application inside (I cannot reproduce here the whole code due to complexity):

```
import Bugsnag from '@bugsnag/expo';
...
const ErrorBoundary = Bugsnag.getPlugin('react');

export const Application = () => (
  <ErrorBoundary>
    {"rest of my application"}
  </ErrorBoundary>
)
```

But when I run the app in debug mode, it crashes with `ErrorBoundary` not being a valid component:
![image](https://user-images.githubusercontent.com/2738569/84316766-f8aa9280-ab6b-11ea-817c-b083dbef9df2.png).

I looked at a [this similar issue](https://github.com/bugsnag/bugsnag-js/issues/494). But it is about `web react`. 
Thank you for your advice.

Specs:

`package.json`
```
     "@bugsnag/expo": "^7.1.1",
     "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
```
`node version: v12.14.0`
`ios, physical device xr 10`

**Comment by johnkiely1** [comment] 2020-06-12 14:11
Hi @seyaobey. 
This is a generic type error thrown if there is a problem with the import of export of the react modules. In this case looks like you need to as `default` as so to fix this error. 

`export **default** const Application = () => (...)`

**Comment by mariasierraloynaz** [comment] 2020-06-24 23:26
I have the exact problem, not an import issue , the error boundary is undefined , as soon I removed it issue gone. so How can get ErrorBoundary  in 7.1?

**Comment by johnkiely1** [comment] 2020-06-29 11:15
Hi @mariasierraloynaz 

Did the above suggestion fix your issue? If not I think it may be worth you emailing in to support@bugsnag.com describing the issue you are facing in a bit more detail as I think you are describing a different issue. 

Thanks

**Comment by MahdiKarimipour** [comment] 2021-04-28 10:26
> I have the exact problem, not an import issue , the error boundary is undefined , as soon I removed it issue gone. so How can get ErrorBoundary in 7.1?

Any luck on this issue raised by @mariasierraloynaz ? I have followed your guide here, and I get the below error.

https://docs.bugsnag.com/platforms/react-native/expo/

TypeError: undefined is not an object (evaluating '_expo.Bugsnag.getPlugin')

**Comment by yousif-bugsnag** [comment] 2021-04-30 07:55
Hi @MahdiKarimipour

Can you provide a simple reproduction case, or alternatively write in to us at support@bugsnag.com with a few more details about the specific issue you're seeing?

**Comment by mattdyoung** [comment] 2021-05-21 11:17
@MahdiKarimipour 
We don't have sufficient information to reproduce this issue and identify the cause so closing this for now. If you could share a minimal example project which demonstrates the issue we'd be very happy to re-open and investigate further.

**Closed by mattdyoung** 2021-05-21 11:17 UTC
Labels: awaiting feedback

**Comment by petarproko** [comment] 2021-06-25 15:07
For those who are still having issues try executing Bugsnag.start() function before ErrorBoundary object.

**Comment by ppeelman** [comment] 2021-08-20 14:03
I had the same issue.
I solved it by moving the getPlugin call within the component:

`export default () => {
    const ErrorBoundary = Bugsnag.getPlugin('react').createErrorBoundary(React);

    return (
            <ErrorBoundary>
                <App/>
            </ErrorBoundary>
    )
}`
