### ISSUE TITLE
Native library could not be linked

### ISSUE THREAD

**Issue by invyctus92** [bugsnag/bugsnag-js#1430] opened 2021-06-04 15:34 UTC
With the latest release of my application and after the Bugsnag update, I have noticed many reports of the following type: 

NdkLinkError: Native library could not be linked. Bugsnag will not report NDK errors. See https://docs.bugsnag.com/platforms/android/ndk-link-errors
        at java.lang.Runtime.loadLibrary0(Runtime.java:972)

AnrLinkError: Native library could not be linked. Bugsnag will not report ANRs. See https://docs.bugsnag.com/platforms/android/anr-link-errors
        at java.lang.Runtime.loadLibrary0(Runtime.java:972)

I've tried following the guide in the link, but it's not very clear and the different tests create an unbootable version. Does anyone know how to fix this ? Thanks 

Note: I'm using Hermes.

Environment

Library versions:

"@bugsnag/react-native": "7.10.1",
"react-native": "0.63.4",

simulator/emulator or physical device?: Physical Device

debug mode or production?: Production

**Comment by johnkiely1** [comment] 2021-06-07 11:51
Hi @invyctus92,  

When using the suggestions described here: https://docs.bugsnag.com/platforms/android/faq/#what-are-anrlinkerror-and-ndklinkerrors those should be called before Bugsnag.start(). 

The underlying problem with loading native libraries occurs due to bugs in Android itself, in certain conditions. We are aware there are still bugs (in later versions of Android) for which the ReLinker fix will not work and are likely to remain until Google fixes these issues. If you still see these errors after implementing the ReLinker fix that is likely the cause. We don't have any other workarounds other than using ReLinker that we can suggest.  

This will also not be limited to Bugsnag libraries as it could happen with any native library however these would likely be manifested as UnsatisfiedLink errors.  In order to prevent a fatal crash, degrade gracefully and maintain some error capture functionality we capture these for Bugsnag libraries and show them as NdkLinkError or AnrLinkError in the dashboard.

**Comment by invyctus92** [comment] 2021-06-07 13:31
Thanks for the technical explanation, but I would need a complete example of a ReLinker implementation in a React native project, I searched and found nothing.

**Comment by johnkiely1** [comment] 2021-06-11 00:02
Hi @invyctus92 

You would just need to add the following ahead of the existing `Bugsnag.start()` call in the `onCreate` callback of your Application subclass (usually in `MainApplication.java`):

```
ReLinker.loadLibrary(this, "bugsnag-ndk");
ReLinker.loadLibrary(this, "bugsnag-plugin-android-anr");

Bugsnag.start(this);
```

**Comment by invyctus92** [comment] 2021-06-11 08:04
I followed your advice but I have an error: 

MainApplication.java:53: error: cannot find symbol ReLinker.loadLibrary(this, "bugsnag-ndk");
MainApplication.java:54: error: cannot find symbol ReLinker.loadLibrary(this, "bugsnag-plugin-android-anr");

` @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
    ReLinker.loadLibrary(this, "bugsnag-ndk");
    ReLinker.loadLibrary(this, "bugsnag-plugin-android-anr");
    Bugsnag.start(this);
    RNBranchModule.getAutoInstance(this);
  }`

**Comment by yousif-bugsnag** [comment] 2021-06-11 11:43
Hi @invyctus92 have you installed Relinker in your project? https://github.com/keepsafe/Relinker#installation

**Comment by invyctus92** [comment] 2021-06-11 12:02
Now I try with adding implementation 'com.getkeepsafe.relinker:relinker:1.4.3' in dependencies in build.gradle but I still have the same error, maybe there is an import missing in MainApplication ? 

I used implementation instead of compile since it was giving me the following error, while implementation was going on. 

Could not find method compile() for arguments [com.getkeepsafe.relinker:relinker:1.4.3] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by xander-jones** [comment] 2021-06-15 15:15
Are you adding the implementation in the `<project>/build.gradle`, and **not** in `<project>/app/build.gradle`? As that would also result in the error above.

**Comment by invyctus92** [comment] 2021-06-15 17:23
Then I had the wrong directory, but now putting compile 'com.getkeepsafe.relinker:relinker:1.4.3' in android/build.gradle, I have the following error: 

Could not find method compile() for arguments [com.getkeepsafe.relinker:relinker:1.4.3] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Maybe I mistake the location of the compile.

Here is a part of my file build.gradle:

`buildscript {
    ext {
        googlePlayServicesLocationVersion = "17.0.0"
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        appCompatVersion = "1.1.0"
        fitnessPlayServices = "20.0.0" 
        authPlayServices =  "19.0.0" 

    }
    repositories {
        google()
        jcenter()
        maven { url 'https://plugins.gradle.org/m2/'}
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.4")
        classpath("com.bugsnag:bugsnag-android-gradle-plugin:5.+")
        classpath 'com.google.gms:google-services:4.3.8'
        compile 'com.getkeepsafe.relinker:relinker:1.4.3'
    }
}`

**Comment by johnkiely1** [comment] 2021-06-18 10:31
Hi @invyctus92, 

I think the Relinker install documentation (readme) is actually somewhat confusing. You should **not** add this to your buildscript section. 

Instead you can add this dependency to your `<project>/app/build.gradle` `dependencies` section so it available to your app module.

You should also look to use `implementation` over `compile` as it has been deprecated.

You should end up with something like the following in your `<project>/app/build.gradle`

```
dependencies {
	//other dependencies..
    implementation "com.bugsnag:bugsnag-android:5.4.0"
    implementation "com.getkeepsafe.relinker:relinker:1.4.3"
}
```

**Comment by invyctus92** [comment] 2021-06-18 16:27
Thank you @johnkiely1 , 
I had already tried this implementation but had a problem in MainApplication, adding ReLinker.loadLibrary::

MainApplication.java:53: error: cannot find symbol ReLinker.loadLibrary(this, "bugsnag-ndk");
MainApplication.java:54: error: cannot find symbol ReLinker.loadLibrary(this, "bugsnag-plugin-android-anr");

`@Override public void onCreate() { super.onCreate(); SoLoader.init(this, /* native exopackage */ false); initializeFlipper(this, getReactNativeHost().getReactInstanceManager()); ReLinker.loadLibrary(this, "bugsnag-ndk"); ReLinker.loadLibrary(this, "bugsnag-plugin-android-anr"); Bugsnag.start(this); RNBranchModule.getAutoInstance(this); }`

**Comment by johnkiely1** [comment] 2021-06-23 08:16
Hi @invyctus92, 

Have you included the import statement in your `MainApplication.java`? 

`import com.getkeepsafe.relinker.ReLinker;`

This is the type of error you would get if that has been omitted.

**Comment by invyctus92** [comment] 2021-06-23 15:37
Added import in MainApplication.java  and now it compiles correctly without errors but won't start node to interpret the code. The android simulator does not start the app.

BUILD SUCCESSFUL in 58s
907 actionable tasks: 2 executed, 905 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...

**Comment by johnkiely1** [comment] 2021-06-25 10:29
Hi @invyctus92, 

Does it compile and run correctly without Relinker? If not I would suggest you start there as it is seems unlikely to be related to Bugsnag/Relinker. There should be some logs somewhere giving you more information as to why the application didn't start. At this point there is nothing to suggest that there is a Bugsnag related issue happening here. Relinker is a third party tool that helps with loading Android libraries, but ultimately the underlying issue is to do with Android native class loading and in some circumstances there is simply nothing you can do about it. 

I will go ahead and close this issue, but feel free to contact us via support@bugsnag.com if you have any further information to suggest this is a Bugsnag related issue.

**Closed by johnkiely1** 2021-06-25 10:29 UTC
Labels: awaiting feedback
