### ISSUE TITLE
Console.log messages all appear from bugsnag-3.min.js:1

### ISSUE THREAD

**Issue by dmorrow** [bugsnag/bugsnag-js#206] opened 2016-10-27 13:58 UTC
Debug messages in my React app on Chrome no longer show their origin file, but rather appear to originate from bugsnag-3.min.js:1

**Comment by eanakashima** [comment] 2016-10-27 15:53
Duplicate of https://github.com/bugsnag/bugsnag-js/issues/156. To be able to add console messages to report them in the breadcrumb timeline, we have to wrap the built-in console functions. This adds bugsnag-js to the stack trace when things log to the console. This [comment](https://github.com/bugsnag/bugsnag-js/issues/156#issuecomment-247687258) describes how to turn console breadcrumbs off if you'd prefer to have the original line numbers instead.

**Closed by eanakashima** 2016-10-27 15:53 UTC
