### ISSUE TITLE
[BUG] - Can not found BSGUIKit.h iOS compile

### ISSUE THREAD

**Issue by cinder92** [bugsnag/bugsnag-js#1246] opened 2021-01-18 04:54 UTC
Hello, im using Circle CI to build my app, im using xcode 12.0.0 and bugsnag for react native 7.5.2 and im getting above issue.

![Screen Shot 2021-01-17 at 22 52 44](https://user-images.githubusercontent.com/4725556/104873782-e4efb780-5916-11eb-9e28-2c3666d63fae.png)

i did `cd ios && pod install`, but no luck, any thoughts ? thanks

**Comment by xander-jones** [comment] 2021-01-18 16:38
Hey @cinder92, does your application run in Debug and Release modes as expected with Bugsnag prior to trying to archive the build? What does the output of `pod install` show?

The right files should be available for you following a successful install of the React Native package using `npm` or `yarn`. From the screenshot it looks like the `Pods` and `node_modules` relative to one another are ok, but they're nested in a second `ios` directory. so it's not clear how your project is laid out. If you're using a non-standard structure, can you please share with us what this looks like to try and reproduce this?

**Comment by mattdyoung** [comment] 2021-02-02 17:09
Closing for now, but do let us know if you have further information to share which may help us diagnose this.

**Closed by mattdyoung** 2021-02-02 17:09 UTC
