### ISSUE TITLE
Cannot read property 'getRemainingTimeInMillis' of undefined

### ISSUE THREAD

**Issue by ldaume** [bugsnag/bugsnag-js#1536] opened 2021-10-01 15:08 UTC
My lambda function on prod ends in a TypeError:
```typescript
export const lambdaHandler: SNSHandler = async (event: SNSEvent, context: Context): Promise<void> => {
   // ...
}

At the end this error occurs:
```json
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read property 'getRemainingTimeInMillis' of undefined",
  "trace": [
    "TypeError: Cannot read property 'getRemainingTimeInMillis' of undefined",
    "    at <anonymous> (/opt/nodejs/node_modules/@bugsnag/plugin-aws-lambda/dist/src/index.js:62:24)",
    "    at null.createMatchingForUnmatchedFreelancersWithSpecificJob (/var/task/src/handlers/ts/xxx/xx-xxx.ts:346:30)",
    "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "    at Runtime.lambdaHandler (/var/task/src/handlers/ts/xxx/xx-xxx.ts:393:3)"
  ]
}
```

It's interesting that the plugin-aws-lambda code contains exactly this problem at https://github.com/bugsnag/bugsnag-js/blob/13cd9d3e45affaf37e3e8098fff6fe7d6a9a486d/packages/plugin-aws-lambda/src/index.js#L60-L64

**Comment by yousif-bugsnag** [comment] 2021-10-04 13:03
Hi @ldaume, in your case it looks like `context` itself is undefined, rather than `getRemainingTimeInMillis`, which is what that code is guarding against. Can you share how you are initialising Bugsnag and wrapping your handler in your Lambda function?

**Comment by mattdyoung** [comment] 2021-11-12 10:15
Closing this for now as we haven't been able to reproduce but if you're able to provide a full reproduction example we'd be happy to investigate further.

**Closed by mattdyoung** 2021-11-12 10:15 UTC
