### ISSUE TITLE
Permission denied to access property "apply"

### ISSUE THREAD

**Issue by Waltari10** [bugsnag/bugsnag-js#469] opened 2019-01-21 13:45 UTC
Hey, 

I am getting the following unhandled error reported on Bugsnag-js. What could be causing it?

We are using: 
    "@bugsnag/js": "^5.0.2",
    "angular": "~1.7.2",

Error
/
Permission denied to access property "apply"
Jan 21st, 2019, 06:37:30 UTC

STACKTRACE

Error Permission denied to access property "apply" 
    ../../../../../node_modules/@bugsnag/browser/plugin-inline-script-content/inline-script-content.js:37:26 init/e.onreadystatechange

**Comment by Waltari10** [comment] 2019-01-21 15:15
It's a fairly large project, so we aren't doing anything with it as far as I know. A global search returned nothing in the project and neither in node_modules.

**Comment by Waltari10** [comment] 2019-01-21 15:19
We aren't doing anything with it specifically, but we have quite a few node_modules that seem to do something with it. These include: @babel/polyfill, angular-ng-truncate, clockpicker, bootstrap-datepicker etc... I found these out by doing a global search on the project. Is there any workaround?

**Comment by Waltari10** [comment] 2019-01-21 15:22
Or can I atleast have the app not crash somehow? This error only occurs very rarely, and I haven't been able to reproduce it.

**Comment by Waltari10** [comment] 2019-01-21 15:44
Could it actually be adblock?

**Comment by Waltari10** [comment] 2019-01-22 05:01
Apparently it's not Adblock Plus or AdBlock for Firefox. This is only happening on Firefox browser version 64.0.0.

**Comment by bengourley** [comment] 2019-01-23 16:47
> I can confirm - experience this in FF Developer Edition v66

Can you reliably reproduce this in your own browser or are you talking about events in your dashboard? Does the browser have any extensions running? Is there a publicly accessible page which you see this occur on?

Answers to any of the above should help us figure this out and work out how best to fix it. Thanks!

**Comment by eugeneoshepkov** [comment] 2019-01-24 10:04
@bengourley It happens in the browser on one of our back-office projects. It turned out that DuckDuckGo extension causes this even if a site is in its whitelist. Only disabling this extension helped.

**Comment by bengourley** [comment] 2019-01-25 10:36
It looks like this should have been fixed in DDG's plugin back in August last year, according to the first release that included [this PR](https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/241). What version of the extension did you get?

**Comment by bengourley** [comment] 2019-01-25 10:42
Looks like the latest version you can get from the Mozilla add-ons website is `2018-6-28`, which predates that fix.

https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/versions/

**Closed** 2019-01-26 15:32 UTC

**Comment by timscott** [comment] 2019-10-25 15:49
I'm getting this error, on Firefox 69.0.0 and 70.0.0:

`node_modules/@bugsnag/browser/dist/bugsnag.js:2275   init/t.onreadystatechange`
```
if (typeof prev === 'function') prev.apply(this, arguments);
```

**Comment by tomlongridge** [comment] 2019-10-25 15:58
@timscott - can you confirm you're using at least version [6.4.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v6.4.1) which includes a fix for #608?

**Comment by timscott** [comment] 2019-10-25 16:00
@tomlongridge - From `Gemfile.lock`: 

`bugsnag (6.11.1)`

**Comment by timscott** [comment] 2019-10-25 16:23
@tomlongridge - Ignore my last comment. That's the server side ruby gem. I'm on 6.4.0. I will upgrade.
