### ISSUE TITLE
bugsnag_react-native:extractReleaseAnnotations randomly fails to execute when building React-Native Android

### ISSUE THREAD

**Issue by akinzalowevidation** [bugsnag/bugsnag-js#2008] opened 2023-09-01 14:37 UTC
### Describe the bug
Building a React-Native Android app fails about 20% of the time with an issue related to `bugsnag_react-native:extractReleaseAnnotations`.

### Steps to reproduce
1. Build react-native application with `@bugsnag/react-native` installed and setup for Android.

### Environment
* Bugsnag version: `7.21.0`
* Browser framework version (if any):
    * React: `18.0.0`
    * React-Native: `0.69.8`
* Device (e.g. iphonex): Android

### Example code snippet 

`android/build.gradle`:
```
classpath("com.bugsnag:bugsnag-android-gradle-plugin:7.+")
```

`android/app/build.gradle`:
```
apply plugin: "com.bugsnag.android.gradle"
```
and
```
bugsnag {
  uploadReactNativeMappings = true
}
```

<details><summary>Error messages:</summary>

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bugsnag_react-native:extractReleaseAnnotations'.
> Could not resolve all files for configuration ':bugsnag_react-native:detachedConfiguration2'.
   > Could not download groovy-3.0.9.jar (org.codehaus.groovy:groovy:3.0.9)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy/3.0.9/groovy-3.0.9.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy/3.0.9/groovy-3.0.9.jar'.
            > Connection reset
```
</details>

**Comment by clr182** [comment] 2023-09-05 09:35
Hi @akinzalowevidation 

The error you have shared with us seems like it originated from the Maven repository. Taking a look at [the Maven status page](https://status.maven.org/) shows that they have been having some intermittent issue recently that may be responsible for the problem(s) you are seeing. 

This error message isn’t something we have seen in the past and we have [also not seen any extended downtime recently ](https://status.bugsnag.com/)which could possible explain this. Can you please verify whether these issues are still occuring?

**Comment by akinzalowevidation** [comment] 2023-09-05 20:12
@clr182 Hi, the issue is still occurring. It has been occurring for about 8 weeks but has been occurring more frequently in the past 2 weeks.

**Comment by mclack** [comment] 2023-10-03 10:29
Hi @akinzalowevidation

Just to clarify, this doesn't seem to be an issue on the BugSnag side. We believe you are likely seeing this issue due to outages at Maven, or due to some more general internet issues on your end.

We’re going to close this issue out, but please feel free to reopen it again if you find evidence that this is caused by BugSnag.

**Closed by mclack** 2023-10-03 10:29 UTC
