### ISSUE TITLE
[react-native][android] NdkLinkError and ArnLinkError with SoLoader.init(this, /* native exopackage */ false);

### ISSUE THREAD

**Issue by tastafur** [bugsnag/bugsnag-js#1075] opened 2020-09-29 11:05 UTC
### Describe the bug
My app react-native report NdkLinkError and ArnLinkError with SoLoader.init(this, /* native exopackage */ false);. This native library of react-native.
https://github.com/bugsnag/bugsnag-react-native/issues/376#issuecomment-517643366

Are you going to do something with this? It contaminates us with information that we do not know if it is an error or not, what do we do?

### Steps to reproduce
![Captura de pantalla 2020-09-29 a las 12 58 23](https://user-images.githubusercontent.com/11853181/94550234-afce3500-0253-11eb-8300-5afb30261d43.png)

### Environment
* Bugsnag version: 7.3.3
* React native version: 0.63.2

**Comment by xander-jones** [comment] 2020-09-29 11:48
Hi @tastafur, notifications based on the Bugsnag native libraries failing to link was added in  https://github.com/bugsnag/bugsnag-android/releases/tag/v5.0.0, in this PR: https://github.com/bugsnag/bugsnag-android/pull/861, which was bundled into `@bugsnag/react-native` in https://github.com/bugsnag/bugsnag-js/releases/tag/v7.3.0

This was added so that the Bugsnag library would let you know that NDK or ANR errors would not be reported from a device because the `.so` library failed to load. This generally happens when an application is installed onto a device with an architecture which the `.apk` was not built for, rather than the application crashing because of the linker error.

If you don't want to receive these errors in future, you can either [discard them through the Bugsnag dashboard](https://docs.bugsnag.com/product/event-usage/#discard-individual-errors), or reject them from being sent from your application in [a callback in your native Android layer](https://docs.bugsnag.com/platforms/react-native/react-native/customizing-error-reports/#updating-events-using-callbacks) by checking if the `event.errors[0].errorClass` is equal to `NdkLinkError`, or `AnrLinkError`.

I'm closing this out as it is expected behaviour, but let us know if you have any other questions.

**Closed by xander-jones** 2020-09-29 11:48 UTC

**Comment by tastafur** [comment] 2020-09-29 12:11
hi @xander-jones, this error your sentry competence if you catch it, I come from sentry and the same error occurred to me for the same android version, model, etc.
Thank you anyway, but with that information I learned that something was wrong

![Captura de pantalla 2020-09-29 a las 14 09 25](https://user-images.githubusercontent.com/11853181/94556513-7dc1d080-025d-11eb-9d6b-71b35a586a42.png)
