### ISSUE TITLE
ReactNative: Xcode 15 build "@bugsnag/react-native": "7.21.0" failed.

### ISSUE THREAD

**Issue by VegaChen-BadtzMaru** [bugsnag/bugsnag-js#2021] opened 2023-10-07 06:42 UTC
Import of C++ module 'Darwin.POSIX.sys.types' appears within extern "C" language linkage specification

**Comment by clr182** [comment] 2023-10-16 09:28
Hi @VegaChen-BadtzMaru 

This issue stems from the use of import statements inside of C files or extern "C" language linkage specifications.
As far as we can tell this is not originating from within the cocoa package. Can you please verify whether you have any import within either of these contexts. It may be worth checking if any header files that you have imported has an extern "C" section that contains any imports like this. 

I’d also like to note that we recommend using an #include over an #import in an objc context.

Reference to Apples module Issues documentation: [Identifying and addressing framework module issues | Apple Developer Documentation](https://developer.apple.com/documentation/xcode/identifying-and-addressing-framework-module-issues)  

If you can verify that imports from your side are not causing this issue then please reach out to us again providing some additional context to this error.

**Comment by samuelcai-chancetop** [comment] 2023-10-17 03:34
The problem is from this line:
<img width="784" alt="6d9998103f9bf6dc1b3326fed81da912" src="https://github.com/bugsnag/bugsnag-js/assets/59716697/42ee76c2-9508-4061-9ccf-17e04db2ec65">
Move it to on top of **#ifdef __cplusplus**, then can pass build.

Looks like on Xcode 15, <sys/types.h> already has **#ifdef __cplusplus extern "C" {**, so duplication causes issue.
Not sure if it's Xcode 15's bug, because if I check the source code of <sys/types.h>, I can't see **extern "C"**.

**Comment by samuelcai-chancetop** [comment] 2023-10-17 03:49
I checked the source code of <sys/types.h>
<img width="710" alt="Screenshot 2023-10-17 at 11 44 55" src="https://github.com/bugsnag/bugsnag-js/assets/59716697/59fc0dac-4d07-4d0d-8179-667aea34f6e4">
But I can't find **extern "C"**, weird. Maybe what's used in build is not exact the same as the source code.

Btw, I do find another <sys/types.h> has extern "C", see this: http://www.sde.cs.titech.ac.jp/~gondow/dwarf2-xml/HTML-rxref/app/gcc-3.3.2/lib/gcc-lib/sparc-sun-solaris2.8/3.3.2/include/sys/types.h.html.

**Comment by mclack** [comment] 2023-10-24 13:51
Hi @samuelcai-chancetop 

Thanks for that additional information.

It does seem that moving the `#include` statements outside the `extern "C"` scope would resolve this issue. As such, we have added an item to our backlog to fix this.

We will make sure to update this thread once a fix has been released.

**Comment by samueljim** [comment] 2023-11-02 06:09
bump. Is there an update on this?

**Comment by clr182** [comment] 2023-11-03 09:03
Hi @samueljim 
No update just yet. Once we do have more information we will update this thread

**Comment by kearneysp19** [comment] 2023-11-09 16:41
Do you have a timetable yet for this fix? It breaks our build as well?

**Comment by samueljim** [comment] 2023-11-09 23:23
> Do you have a timetable yet for this fix? It breaks our build as well?

The fix already has a PR over here https://github.com/bugsnag/bugsnag-cocoa/pull/1603

**Comment by clr182** [comment] 2023-11-17 08:56
Hi 👋 
Thank you for your patience as we investigated this. We have just released a new version of our cocoa notifier. [v6.27.3](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.27.3) should fix this issue. Please let us know if you continue to see this behaviour after updating.

**Comment by clr182** [comment] 2023-11-23 09:37
Hi 👋  
A new version of the [Bugsnag-js notifier](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.22.2) has been released which bumps [the version ](https://bugsnag.zendesk.com/agent/tickets/66333)of the cocoa notifier used by the JS notifier. This update to the cocoa notifier involves removes include directives from inside of extern "C" sections. 
Once upgraded, if you are see any issues please let us know and we can investigate further.

**Closed by clr182** 2023-11-23 09:37 UTC
Labels: released
