### ISSUE TITLE
React Native doesn't reporting unhandled error

### ISSUE THREAD

**Issue by npjoge** [bugsnag/bugsnag-js#1603] opened 2021-11-30 06:52 UTC
### Describe the bug
We have configured our React-Native project for BugSnag & its working properly with Handled error & it reporting details with breadCrumbs properly.
But in case of unhandled exception of Android or IOS app, its not reporting Native or JS exceptions.

### Environment
* Bugsnag version: 7.14.0
* React Native version: 0.63.4

**Comment by tradebulls** [comment] 2021-11-30 08:49
We are facing the same issue. Logs and breadcrumbs are getting logged but no crashes for RN and Native are being logged. Any help?

**Comment by luke-belton** [comment] 2021-11-30 10:25
Hi @npjoge - I'm unable to reproduce this with the versions of Bugsnag/React Native that you quoted. Are you running your app in debug or release mode?

As [per our docs](https://docs.bugsnag.com/platforms/react-native/react-native/#reporting-unhandled-errors) the React Native error screen can interfere with reporting of unhandled errors in debug mode.

If this isn't the problem and you're able to give me some more details or a cut-down reproduction example then we'd be happy to look into this. Feel free to write into support@bugsnag.com if you'd prefer 👍

**Comment by npjoge** [comment] 2021-12-01 07:39
@luke-belton I have tried in both mode Release & Debug. In both mode its not reporting unhandled error.

### Example Code for Crash
something.callme();

**Comment by xander-jones** [comment] 2021-12-01 11:13
Hey @npjoge, unhandled exceptions are sent on the next launch of the application. Are you re-launching the application? How are you configuring Bugsnag? Is Bugsnag instantiated prior to you throwing an exception? 

You can find an example using Bugsnag and RN 0.63 which shows how to instantiate and capture unhandled errors here: https://github.com/bugsnag/bugsnag-js/tree/next/examples/reactnative/rn063example

**Comment by mattdyoung** [comment] 2021-12-17 11:09
Closing as we haven't been able to reproduce the issue. I'd suggest writing in to support@bugsnag.com if you're still having issues reporting unhandled errors.

**Closed by mattdyoung** 2021-12-17 11:09 UTC
