### ISSUE TITLE
domain is deprecated

### ISSUE THREAD

**Issue by jigfox** [bugsnag/bugsnag-js#889] opened 2020-06-22 13:57 UTC
We have tried to use @bugsnag/plugin-express with the express part in an angular universal application. But currently the middleware is not working. The app crashes with

```
ERROR in ./node_modules/@bugsnag/plugin-express/dist/bugsnag-express.js
Module not found: Error: Can't resolve 'domain' in 'APPLICATION/node_modules/@bugsnag/plugin-express/dist'
```

I am not sure about the reason of the crash, could be some specialty in angular-universal, but upon looking up what `domain` is and does, we saw it is deprecated sind node v10: https://nodejs.org/docs/latest-v10.x/api/domain.html

**Comment by johnkiely1** [comment] 2020-06-23 14:22
Hi @jigfox.
Thanks for this, we are aware that `domain` is deprecated, and as you rightly say it has been for some time. The problem is that it has not been replaced yet, with anything suitable. Most likely this is why it has not yet been removed from the node codebase. While not ideal this is what we have to work with and is still available for now.

In terms of your application error, are you trying to compile for the browser? If so that is likely to be the issue as `domain` doesn't exist in the browser and would not be found.

**Comment by phillipsam** [comment] 2020-07-08 13:06
Closing this for now as we have not had a response. Do let us know if you would like to follow up on this.

**Closed by phillipsam** 2020-07-08 13:06 UTC
Labels: awaiting feedback
