### ISSUE TITLE
Project with path ':bugsnag_react-native' could not be found in project ':app'.

### ISSUE THREAD

**Issue by enigmablue** [bugsnag/bugsnag-js#1591] opened 2021-11-20 03:40 UTC
ok

### Describe the bug
I am trying to upgrade my gradle to 7.x but i keep getting this error. I tried to search the entire project but there is no mention of a bugsnag_react-native. 

`Caused by: org.gradle.api.UnknownProjectException: Project with path ':bugsnag_react-native' could not be found in project ':app'.
`

Tried
1. delete / re-install node modules
2. Invalidate cache and restart on android studio

### Steps to reproduce
Just try to sync in android studio

### Environment
* Bugsnag version: "@bugsnag/react-native": "^7.11.0",
    "@bugsnag/react-native-cli": "^7.10.5", 
"react-native": "0.63.3",

**Comment by mattdyoung** [comment] 2021-11-22 15:42
Hi @enigmablue 

Can you upgrade to the latest `@bugsnag/react-native` and confirm whether you still see the issue as we've shipped a number of fixes since the version you're using:
https://github.com/bugsnag/bugsnag-js/releases

Also, if your `node_modules` is in a non-standard location you'll need to specify that in your app's `build.gradle`:
https://docs.bugsnag.com/build-integrations/gradle/#custom-node_modules-directory

If you're still seeing issues then it would be useful if you could share further details of your project including your `build.gradle` so we can try and reproduce. Feel free to email support@bugsnag.com if you'd rather not share these publicly.

Thanks!

**Comment by mattdyoung** [comment] 2021-12-07 10:52
Closing as we haven't had a response, but we'd be happy to investigate further if you can confirm this affects the latest version and share the other details which would help us try to reproduce the issue.

**Closed by mattdyoung** 2021-12-07 10:52 UTC
