### ISSUE TITLE
@bugsnag/plugin-angular supports angular 16

### ISSUE THREAD

**Issue by hijamoya** [bugsnag/bugsnag-js#1959] opened 2023-05-08 05:19 UTC
As angular 16 does not support "View Engine" library.

@bugsnag/plugin-angular should be upgraded to use Ivy distribution.

This is the warning:

```
Processing legacy "View Engine" libraries:
- @bugsnag/plugin-angular [es2015/esm2015] (git+ssh://git@github.com/bugsnag/bugsnag-js.git)
Encourage the library authors to publish an Ivy distribution.
```

Thanks!

**Comment by johnkiely1** [comment] 2023-05-12 13:50
Hi @hijamoya, we are going to investigate this and try and reproduce. 

The Angular 16 docs suggest that support for "View Engine" libraries is dropped completely so could produce an error.

Can you confirm this is just a warning rather than an error?

**Comment by hijamoya** [comment] 2023-05-12 15:03
Since ngcc is gone, "View Engine" can not be compiled. It will produce an error.

**Comment by JesseZomer** [comment] 2023-05-16 09:11
Any update on this? This is also preventing us from updating

**Comment by mclack** [comment] 2023-05-16 13:38
Hi @hijamoya, I’ve been able to replicate the warning you are seeing for Angular v15. After upgrading to v16 I have found that BugSnag still works, and no errors or warnings regarding Ivy are being displayed when the app is compiled.

If you are seeing the error using v16 can you tell us how you created the project and/or if you changed any of the default settings?

**Comment by adnan-kamili** [comment] 2023-05-29 13:19
We tried adding bugsnag to our Angular 16 app, but all the requests just timeout (session as well as notify). Any ideas why this is happening? I am able to access bugsnag website/dashboard from the same browser where I am getting this error.

![image](https://github.com/bugsnag/bugsnag-js/assets/1573517/e35a7b8a-e256-4248-81fd-49b39232fbc9)

**Comment by vmalvaro** [comment] 2023-05-30 07:27
Hi @mclackm, even if it works (I didn't try it yet)  would be good to make it compatible and not a View Engine library.

As in Angular document says `Due to the removal of the Angular Compatibility Compiler (ngcc) in v16, projects on v16 and later no longer support View Engine libraries.`

Thanks!

**Comment by AgustinCocconi** [comment] 2023-05-31 21:07
Hello. I'm also trying to compile on an angular 15 app and I get this

Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- @bugsnag/plugin-angular [es2015/esm2015] (git@github.com:bugsnag/bugsnag-js.git)
Error: Error on worker #1: TypeError: Cannot set property getExpandoInitializer of #<Object> which has only a getter
    at patchTsGetExpandoInitializer (file:///C:/Github/cb_website/node_modules/@angular/compiler-cli/bundles/chunk-LRE5KIJ7.js:2601:29)
    at isTs31778GetExpandoInitializerFixed (file:///C:/Github/cb_website/node_modules/@angular/compiler-cli/bundles/chunk-LRE5KIJ7.js:2621:43)
    at patchTsGetExpandoInitializer (file:///C:/Github/cb_website/node_modules/@angular/compiler-cli/bundles/chunk-LRE5KIJ7.js:2594:7)
    at makeBundleProgram (file:///C:/Github/cb_website/node_modules/@angular/compiler-cli/bundles/chunk-LRE5KIJ7.js:2700:41)
    at makeEntryPointBundle (file:///C:/Github/cb_website/node_modules/@angular/compiler-cli/bundles/chunk-LRE5KIJ7.js:2891:15)
    at file:///C:/Github/cb_website/node_modules/@angular/compiler-cli/bundles/chunk-LRE5KIJ7.js:4762:22
    at Worker.<anonymous> (file:///C:/Github/cb_website/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:71:24)
    at Worker.emit (node:events:513:28)
    at process.<anonymous> (node:internal/cluster/worker:35:12)
    at process.emit (node:events:513:28)
    at ClusterMaster.onWorkerMessage (file:///C:/Github/cb_website/node_modules/@angular/compiler-cli/bundles/chunk-37YYFKDO.js:1469:15)
    at file:///C:/Github/cb_website/node_modules/@angular/compiler-cli/bundles/chunk-37YYFKDO.js:1379:71
    at EventEmitter.<anonymous> (file:///C:/Github/cb_website/node_modules/@angular/compiler-cli/bundles/chunk-37YYFKDO.js:1539:15)
    at EventEmitter.emit (node:events:513:28)
    at Worker.<anonymous> (node:internal/cluster/primary:171:13)
    at Worker.emit (node:events:513:28)
    at ChildProcess.<anonymous> (node:internal/cluster/worker:35:12)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:946:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)

**Comment by johnkiely1** [comment] 2023-06-05 10:09
Hi @AgustinCocconi, in order to keep this thread clean and related to Angular 16 support can you please also write in to us at  [support@bugsnag.com](mailto:support@bugsnag.com) and provide as much detail as you can around the circumstances when this occurs along with your bugsnag configuration code and any relevant project setup details.

Thanks

**Comment by clr182** [comment] 2023-11-15 10:14
Hi,

As this issue hasn't seen any activity for some time I will be closing it out. Please feel free to reopen if there are any further questions.

**Closed by clr182** 2023-11-15 10:14 UTC
Labels: awaiting feedback
