### ISSUE TITLE
Incompatibility with Expo SDK 44 + EAS Updates

### ISSUE THREAD

**Issue by kennethlynne** [bugsnag/bugsnag-js#1683] opened 2022-02-01 20:13 UTC
### Describe the bug
`TypeError: null is not an object (evaluating 'Constants.manifest.logUrl')`

### Steps to reproduce
Use EAS updates instead of legacy updates and Constants.manifest will be null, and Constants.manifest2 will instead be defined

### Environment
* Bugsnag version:  "@bugsnag/expo": "7.16.0",

	```
    "expo": "44.0.3",
    "expo-application": "4.0.1",
    "expo-constants": "13.0.1",
    "expo-device": "4.1.0",
    "expo-updates": "0.11.5",
	```

**Comment by kennethlynne** [comment] 2022-02-01 20:25
We're using this patch (applied with patch-package) as a temporary workaround.

```
diff --git a/node_modules/@bugsnag/expo/src/notifier.js b/node_modules/@bugsnag/expo/src/notifier.js
index c991137..ec12668 100644
--- a/node_modules/@bugsnag/expo/src/notifier.js
+++ b/node_modules/@bugsnag/expo/src/notifier.js
@@ -28,7 +28,7 @@ const internalPlugins = [
   require('@bugsnag/plugin-expo-device'),
   require('@bugsnag/plugin-expo-app'),
   require('@bugsnag/plugin-console-breadcrumbs'),
-  require('@bugsnag/plugin-network-breadcrumbs')([NET_INFO_REACHABILITY_URL, Constants.manifest.logUrl]),
+  require('@bugsnag/plugin-network-breadcrumbs')([NET_INFO_REACHABILITY_URL, ...(Constants.manifest ? [Constants.manifest.logUrl] : [])]),
   require('@bugsnag/plugin-react-native-app-state-breadcrumbs'),
   require('@bugsnag/plugin-react-native-connectivity-breadcrumbs'),
   require('@bugsnag/plugin-react-native-orientation-breadcrumbs'),
```

**Comment by kennethlynne** [comment] 2022-02-01 22:01
Some of the relevant usages that needs to be patched:
- https://github.com/bugsnag/bugsnag-js/blob/02730ba4683cfbff8babf6741acd00c7bdc12424/packages/expo/src/notifier.js#L31
- https://github.com/bugsnag/bugsnag-js/blob/84cf0f4c122cf104139f97d5d60775b62b661fc5/packages/plugin-expo-app/app.js#L32
- https://github.com/bugsnag/bugsnag-js/blob/02730ba4683cfbff8babf6741acd00c7bdc12424/packages/expo/src/config.js#L10
- https://github.com/bugsnag/bugsnag-js/blob/84cf0f4c122cf104139f97d5d60775b62b661fc5/packages/plugin-expo-device/device.js#L34

**Comment by luke-belton** [comment] 2022-02-02 14:13
Hi @kennethlynne -`bugsnag-js` doesn't support EAS updates at this stage. There's some more discussion on this over at https://github.com/bugsnag/bugsnag-js/issues/1600 for a bit more info, but I'm going to close this as it doesn't appear to be an issue with something we officially support.

**Closed by luke-belton** 2022-02-02 14:13 UTC

**Comment by kennethlynne** [comment] 2022-02-02 15:29
You should prioritize it as it is going to be the default way for many teams to build their app. Would hate to move away from bugsnag love the product and rely on it for the rest of the infrastructure, but we're not going to let bugsnag hold us back. Luckily able to move forward by just applying the patch mentioned for now

**Comment by brentvatne** [comment] 2022-02-03 21:39
@kennethlynne - EAS Update is still in preview. It's something that we at Expo and the folks at Bugsnag can work on supporting together as it progresses.

**Comment by kennethlynne** [comment] 2022-02-03 22:06
True, gotcha! 👍

**Comment by kennethlynne** [comment] 2022-02-04 10:56
Was a bit grumpy from debugging issues related to EAS channels, dev clients and bugsnag for hours when commenting, but I've had my coffee now. Good point, it is still in preview @brentvatne 😂

Related thread: https://forums.expo.dev/t/custom-dev-client-extra-variables-are-undefined/61414/8

**Comment by thorbenprimke** [comment] 2022-02-04 18:28
@kennethlynne - thanks for raising this issue. I was running into the same issues integrating it. 

One question: Did you run into a problem with building a dev-client for device (developmentClient=true, distribution=internal)? 

```
› Executing MyNewAppName » Bundle React Native code and images
1458
    the transform cache was reset.
1459
❌  (../../../../Library/Developer/Xcode/DerivedData/MyNewAppName-gsjiiyfvwhxuudezgxrxjjzghalf/Build/Intermediates.noindex/ArchiveIntermediates/MyNewAppName/BuildProductsPath/Debug-iphoneos/main.jsbundle:270034:25)

  270032 |       hexToRgb: {
  270033 |         value: function value(hex) {
> 270034 |           var matches = /(?<colorString>[a-f\d]{6}|[a-f\d]{3})/i.exec(hex.toString(16));
         |                         ^ Invalid regular expression: Quantifier has nothing to repeat
  270035 | 
  270036 |           if (!matches) {
  270037 |             return [0, 0, 0];
1460
› Generating debug MyNewAppName » MyNewAppName.app.dSYM

```

EAS builds other targets successfully -  dev-client for simulator and internal preview (developmentClient=false, distribution=internal).

**Comment by kennethlynne** [comment] 2022-02-04 19:32
We have not seen anything like that and we're able to build our dev client successfully with bugsnag atm.

Some relevant dependencies and set up confirmed to work for us (since I have no idea what else might be the problem):

```
    "@bugsnag/expo": "7.16.0",
    "@expo/metro-config": "0.3.8",
    "expo": "44.0.5",
    "expo-analytics-segment": "11.1.0",
    "expo-application": "4.0.1",
    "expo-blur": "11.0.0",
    "expo-camera": "12.1.0",
    "expo-clipboard": "2.1.0",
    "expo-community-flipper": "44.0.0",
    "expo-constants": "13.0.1",
    "expo-dev-client": "0.8.3",
    "expo-dev-menu-interface": "0.5.2",
    "expo-device": "4.1.0",
    "expo-document-picker": "10.1.1",
    "expo-file-system": "13.1.2",
    "expo-image-picker": "12.0.1",
    "expo-keep-awake": "10.0.1",
    "expo-linear-gradient": "11.0.1",
    "expo-linking": "3.0.0",
    "expo-localization": "12.0.0",
    "expo-media-library": "14.0.1",
    "expo-notifications": "0.14.0",
    "expo-secure-store": "11.1.0",
    "expo-sharing": "10.1.0",
    "expo-splash-screen": "0.14.1",
    "expo-status-bar": "1.2.0",
    "expo-tracking-transparency": "2.1.0",
    "expo-updates": "0.11.6",
    "expo-web-browser": "10.1.0",
```
```
    "@babel/cli": "7.16.7",
    "@babel/core": "7.16.7",
    "@babel/preset-typescript": "7.16.7",
    "@expo/config": "6.0.6",
```
babel.config.js
```
module.exports = function (api) {
  api.cache(true)

  return {
    presets: ['babel-preset-expo'],
    plugins: [
      'transform-inline-environment-variables',
      'react-native-reanimated/plugin',
    ],
  }
}

```
@thorbenprimke

**Comment by thorbenprimke** [comment] 2022-02-04 19:46
@kennethlynne - thanks for the quick reply and sharing your dependencies. Lemme give this one more try. 

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2Fqjr1ZNLWEVvg9aFCyL%2Fgiphy.gif&token=noteasy" data-gitmeme-token="noteasy"><img src="https://media2.giphy.com/media/qjr1ZNLWEVvg9aFCyL/giphy.gif" title="Created by gitme.me with /noteasy"/></a>

**Comment by kennethlynne** [comment] 2022-02-04 20:19
Please note @thorbenprimke that the patch I initially suggested is partially incorrect. Here is a PR that improves the patch https://github.com/bugsnag/bugsnag-js/pull/1686
I won't spend more time on expanding tests before @luke-belton confirms that they will consider getting this change in.

**Comment by thorbenprimke** [comment] 2022-02-08 19:59
I got around to digging into it further. The exception ([a similar one here](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3371)) itself happens because [Hermes](https://github.com/facebook/hermes/issues/46) does not support named groups in regex functions. 

The dependency on the [ansi-styles](https://github.com/chalk/ansi-styles/blob/2ceace1882ce48b6fc71cb4e6c092f1896563b98/index.js) library that contains the regex was already in our codebase - dependency of Jest. And Jest is only a dev dependency.

However removing Jest resolved the build issue. I have also verified that just adding Bugsnag (as a dependency) and Jest (as a dev dependency) reproduces the build failure with a fresh Expo project building on EAS. 

Maybe I missed something along the way but that's where I got to.

**Comment by Christopher2K** [comment] 2022-04-21 21:44
Hi, I'm posting here as it can help devs who are stuck on this issue.

Thanks a lot @thorbenprimke for you investigation. 

A short term solution would be installing this babel plugin `babel-plugin-transform-modern-regexp` to enable the missing feature for Hermes.

Credits: https://github.com/facebook/hermes/issues/231#issuecomment-951922268

**Comment by thorbenprimke** [comment] 2022-04-22 16:41
@Christopher2K - thanks for leaving that tip. I'll give it a try.
