### ISSUE TITLE
Android with Hermes enabled fails to bundle JS

### ISSUE THREAD

**Issue by lwise** [bugsnag/bugsnag-js#1549] opened 2021-10-20 23:35 UTC
### Describe the bug

When running the task `./gradlew bundleDebugJsAndAssets` for an Android project with Hermes enabled, the task fails on a named capture group in a regular expression.

This is due to the use of the `pretty-format` library (and transitively `ansi-styles`) in the code copied from an old version of `react-native` in https://github.com/bugsnag/bugsnag-js/blob/next/packages/plugin-react-native-unhandled-rejection/rejection-handler.js

Hermes has no current plans to support the named capture groups that `ansi-styles` is using: https://github.com/facebook/hermes/issues/89

`ansi-styles` has no plans to change for compatibility with Hermes: https://issuehunt.io/r/chalk/ansi-styles/issues/76

### Steps to reproduce

On an Android project with the below environment setup...
1. Install `@bugsnag/react-native` into the project's React Native entrypoint as per the [Bugsnag Integration Guide](https://docs.bugsnag.com/platforms/react-native/react-native/)
2. Run `./gradlew bundleDebugJsAndAssets` (or your project's equivalent) with Hermes enabled

### Environment
* Bugsnag version: `7.13.1`
* React Native version: `0.65.1`
* Hermes version: `0.8.1`

### Example code snippet 

We are able to work around the problem by simply patching the `pretty-format` requirement out in post-install:
```
--- ../node_modules/@bugsnag/plugin-react-native-unhandled-rejection/rejection-handler.js.original
+++ ../node_modules/@bugsnag/plugin-react-native-unhandled-rejection/rejection-handler.js
@@ -40,7 +40,7 @@ const rnInternalOnUnhandled = (id, rejection) => {
     stack = error.stack
   } else {
     try {
-      message = require('pretty-format')(rejection)
+      message = rejection
     } catch {
       message =
         typeof rejection === 'string'
@@ -55,3 +55,4 @@ const rnInternalOnUnhandled = (id, rejection) => {
     (stack == null ? '' : stack)
   console.warn(warning)
 }
```

<details><summary>Error messages:</summary>

```
/app/android/Shopify/build/generated/assets/react/google/debug/index.android.bundle:112147:25: error: Invalid regular expression: Quantifier has nothing to repeat
--
  |  
  | var matches = /(?<colorString>[a-f\d]{6}\|[a-f\d]{3})/i.exec(hex.toString(16));
  |  
  | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  |  
  |  
  |  
  | FAILURE: Build failed with an exception.
  |  
  |  
  |  
  | * Where:
  |  
  | Script '/app/node_modules/react-native/react.gradle' line: 182

```
</details>

**Comment by mattdyoung** [comment] 2021-11-08 14:04
Closing this as we've been unable to reproduce but we'd be very happy to investigate further if more details are available.

**Closed by mattdyoung** 2021-11-08 14:04 UTC
Labels: awaiting feedback

**Comment by lwise** [comment] 2021-11-08 14:48
Thanks, I may come back to this but I haven't had the bandwidth to create a sample project yet.
