### ISSUE TITLE
Bugsnag gradle plugin doesn't work with Android gradle plugin 4.2+

### ISSUE THREAD

**Issue by AndrewMorsillo** [bugsnag/bugsnag-js#1100] opened 2020-10-16 16:47 UTC
### Describe the bug
When using Android gradle plugin 4.2+ the Bugsnag gradle plugin causes the build to fail. It works with 4.1.0. The failure is:

```
java.lang.ClassCastException: com.android.build.api.component.analytics.AnalyticsEnabledApplicationVariantBuilder_Decorated cannot be cast to com.android.build.api.variant.Variant
```

### Steps to reproduce
1. Add bugsnag to a react-native android app
2. Add the gradle plugin 
3. Use android gradle plugin `'com.android.tools.build:gradle:4.2.0-alpha13'`
4. Gradle commands now fail

### Environment
* Bugsnag version: `"@bugsnag/react-native": "^7.5.0"`
* React Native 0.63.3
* Browser framework version (if any): N/A
    * Vue:
    * React:
    * Angular:
* Server framework version (if any): N/A
    * Koa:
    * Express:
    * Restify:
* Browser version (e.g. chrome, safari): N/A
* Device (e.g. iphonex): N/A

### Example code snippet 

```
See above, use AGP 4.2+ to trigger error
```

**Comment by phillipsam** [comment] 2020-10-20 09:03
@AndrewMorsillo thanks for the report. I believe this issue is a duplicate of https://github.com/bugsnag/bugsnag-android-gradle-plugin/issues/319. Closing here and continuing to track on that issue.

**Closed by phillipsam** 2020-10-20 09:03 UTC
