### ISSUE TITLE
Maximum call stack size exceeded with @bugsnag/plugin-angular in SSR

### ISSUE THREAD

**Issue by axelboc** [bugsnag/bugsnag-js#455] opened 2018-12-21 12:00 UTC
Following #441, I'm now getting `RangeError: Maximum call stack size exceeded` during server-side rendering in Angular.

![capture d ecran 2018-12-21 a 12 49 14](https://user-images.githubusercontent.com/2936402/50341467-330b1480-051f-11e9-84a1-eee8fc509816.png)

```json
{
  "@bugsnag/js": "^5.1.0",
  "@bugsnag/plugin-angular": "^5.1.0"
}
```

```ts
// core.module.ts

import bugsnag from '@bugsnag/js';
import { BugsnagErrorHandler } from '@bugsnag/plugin-angular';

const bugsnagClient = bugsnag({ ... });

export function errorHandlerFactory() {
  return new BugsnagErrorHandler(bugsnagClient);
}

@NgModule({
  ...
  providers: [
    { provide: ErrorHandler, useFactory: errorHandlerFactory },
    ...
  ]
})
export class CoreModule {}
```

```ts
// core.server.module.ts

import { CoreModule } from '@core/core.module';

@NgModule({
  imports: [
    CoreModule,
    ...
  ]
})
export class CoreServerModule {}
```

If I'm not mistaken, since `@bugsnag/js` is universal, it doesn't need to be initialised differently for server-side rendering, does it?

**Comment by bengourley** [comment] 2018-12-21 14:41
There doesn't appear to be any `@bugsnag/node` frames in the stacktrace you showed there…?

Our example app runs with SSR (using the command `ng serve --aot`) which I have confirmed to be working.

The library is universal, yes, and it doesn't need to be initialised differently for SSR. Does your error go away when you remove Bugsnag?

**Comment by axelboc** [comment] 2018-12-21 15:15
Yeah, if I remove Bugsnag, everything works fine.

The app is served with Express, as explained in Angular's documentation - https://angular.io/guide/universal#step-4-set-up-a-server-to-run-universal-bundles

The error comes up as soon as I start the server with `node`.

**Comment by bengourley** [comment] 2018-12-21 15:54
How does your app differ from our [example](https://github.com/bugsnag/bugsnag-js/tree/next/examples/angular)? Can you provide a simple repo where this issue can be reproduced?

**Comment by axelboc** [comment] 2019-01-08 09:39
Happy New Year! 🎉

Your example is based on **Angular 5.2 without server-side rendering**. My project is based on **Angular 7.1 with server-side rendering**. We followed this guide pretty much to the letter to set up the SSR part: https://angular.io/guide/universal.

Would you be able to please add an example of this set-up to your repo, or to upgrade your current example? I'm pretty sure it will reveal the issue right away.

**Comment by oleksmir** [comment] 2019-02-27 11:31
@axelboc Which version on nodejs do you use? 

I faced with this bug on nodejs version 10.15.0. After downgrading to 8.15.0 everything became ok. Also I need to mention that SSR guide from angular page uses express with nodejs 8 runtime. Maybe this would help you.

**Comment by axelboc** [comment] 2019-02-27 12:47
Indeed, I'm on Node 10.15.1. Good to know about v8, thanks! I'd still love to get it working on v10, though.

**Comment by axelboc** [comment] 2019-03-19 15:46
Thanks @oleksmir, I did manage to update to `@bugsnag/js` on Node 10 without getting the error by initialising Bugsnag only in the browser. Not ideal since I have errors in SSR that are still not reported, but at least I'm up to date.

**Comment by bengourley** [comment] 2019-05-16 14:37
I've been investigating this issue and cannot reproduce it. I used the project on this page: https://angular.io/guide/universal

Using node v10.15.1, here are the versions of the top-level dependencies that got installed:

```
angular-io-example@1.0.0 /Users/bengourley/Development/universal-angular
├── @angular-devkit/build-angular@0.11.4
├── @angular/animations@7.2.15
├── @angular/cli@7.3.9
├── @angular/common@7.2.15
├── @angular/compiler@7.2.15
├── @angular/compiler-cli@7.2.15
├── @angular/core@7.2.15
├── @angular/forms@7.2.15
├── @angular/http@7.2.15
├── @angular/platform-browser@7.2.15
├── @angular/platform-browser-dynamic@7.2.15
├── @angular/platform-server@7.2.15
├── @angular/router@7.2.15
├── @angular/upgrade@7.2.15
├── @bugsnag/js@6.2.0
├── @bugsnag/plugin-angular@6.2.0
├── @nguniversal/express-engine@7.1.1
├── @nguniversal/module-map-ngfactory-loader@7.1.1
├── @types/jasmine@2.8.16
├── @types/jasminewd2@2.0.6
├── @types/node@8.9.5
├── angular-in-memory-web-api@0.8.0 (github:brandonroberts/in-memory-web-api-bazel#50a34d84b627ec88816242dec77603d6dcb9c880)
├── core-js@2.6.5
├── jasmine-core@2.99.1
├── jasmine-spec-reporter@4.2.1
├── karma@3.0.0
├── karma-chrome-launcher@2.2.0
├── karma-coverage-istanbul-reporter@2.0.5
├── karma-jasmine@1.1.2
├── karma-jasmine-html-reporter@0.2.2
├── lodash@4.17.11
├── protractor@5.4.2
├── rxjs@6.5.2
├── ts-loader@4.5.0
├── ts-node@7.0.1
├── tslint@5.11.0
├── typescript@3.1.6
├── webpack-cli@3.3.2
└── zone.js@0.8.29
```

Error reporting works on the server and in the browser, and the node process not crash (unless I throw an error and make it).

Closing this off as it looks like this is no longer an issue. Please feel free to post steps to reproduce if you are still seeing an issue like this and believe Bugsnag to be the cause.

**Closed by bengourley** 2019-05-16 14:37 UTC
Labels: scheduled
